/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PnrRouteImport } from './routes/pnr'
import { Route as TrainsRouteImport } from './routes/trains'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBookTrainIdRouteImport } from './routes/_authenticated/book.$trainId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PnrRoute = PnrRouteImport.update({
  id: '/pnr',
  path: '/pnr',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookTrainIdRoute =
  AuthenticatedBookTrainIdRouteImport.update({
    id: '/book/$trainId',
    path: '/book/$trainId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pnr': typeof PnrRoute
  '/trains': typeof TrainsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/book/$trainId': typeof AuthenticatedBookTrainIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pnr': typeof PnrRoute
  '/trains': typeof TrainsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/book/$trainId': typeof AuthenticatedBookTrainIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pnr': typeof PnrRoute
  '/trains': typeof TrainsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/book/$trainId': typeof AuthenticatedBookTrainIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pnr'
    | '/trains'
    | '/admin'
    | '/bookings'
    | '/book/$trainId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pnr'
    | '/trains'
    | '/admin'
    | '/bookings'
    | '/book/$trainId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pnr'
    | '/trains'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/_authenticated/book/$trainId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PnrRoute: typeof PnrRoute
  TrainsRoute: typeof TrainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnr': {
      id: '/pnr'
      path: '/pnr'
      fullPath: '/pnr'
      preLoaderRoute: typeof PnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$trainId': {
      id: '/_authenticated/book/$trainId'
      path: '/book/$trainId'
      fullPath: '/book/$trainId'
      preLoaderRoute: typeof AuthenticatedBookTrainIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBookTrainIdRoute: typeof AuthenticatedBookTrainIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBookTrainIdRoute: AuthenticatedBookTrainIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PnrRoute: PnrRoute,
  TrainsRoute: TrainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
